<?php
return [
    'length' => 'The length converter can automatically convert measurement values of all different units of length, including metric units such as kilometers (km), meters (m), centimeters (cm), millimeters (mm), micrometers (μm), nanometers (nm), as well as imperial units such as yards (yd), feet (ft), inches (in), furlongs (fur), and miles (mi).',
    'weight' => 'Weight conversion can automatically convert all different units of mass measurement, including metric units such as grams (g), kilograms (kg), metric tons (mt), as well as imperial units such as ounces (oz), pounds (lb), long tons (LT), and short tons (ST).',
    'temperature' => 'Temperature conversion can automatically convert all different units of temperature, including Celsius (°C), Fahrenheit (°F), Kelvin (K), and Rankine (°R).',
    'conversion_calculator' => 'This tool provides a simple and user-friendly unit conversion feature, allowing you to easily convert between different types of measurement units such as length, weight, temperature, and more.',
    'disclaimer_1' => 'Welcome to "Banshus" (hereinafter referred to as "the Website"). Please note that by browsing the Website, you agree to the following terms:',
    'disclaimer_2' => 'Risk Disclaimer: All content provided on the Website is for reference only. Users of the Website assume all risks associated with the use of its content, and the Website shall not be held responsible.',
    'disclaimer_3' => 'Accuracy of Content: While every effort has been made to provide accurate content, the Website does not guarantee its accuracy or reliability. The Website shall not be liable for any errors or omissions in the content and reserves the right to change the content at any time without prior notice.',
    'disclaimer_4' => 'Website Services: The Website reserves the right to suspend or change web page data and related terms at any time without prior notice to users.',
    'disclaimer_5' => 'Disclaimer of Liability: The Website shall not be liable for any damages arising from the use of or connection to the Website, including but not limited to computer viruses, system failures, or data loss. The Website shall not be liable for any damages resulting from defamation, copyright infringement, or intellectual property infringement, including but not limited to loss of profits, loss of reputation, data loss, or other intangible losses, whether direct, indirect, incidental, special, consequential, or punitive.',
    'area' => 'The area conversion tool automatically converts between various units of area, including metric units such as hectares (ha), square kilometers (km²), square meters (m²), square centimeters (cm²), and imperial units such as square yards (yd²), square feet (ft²), and square inches (in²).',
    'bmi' => 'Body Mass Index (BMI) is an indicator used to measure the relationship between a person\'s weight and height. The BMI formula calculates by dividing a person\'s weight (in kilograms) by the square of their height (in meters). Typically, BMI is used to assess whether a person is underweight, normal weight, overweight, or obese.',
    'body_fat' => 'Body fat percentage is the percentage of body fat compared to total body weight. It reflects how much body fat one has and is commonly used to assess obesity. However, body fat percentage is not a fixed value and can vary depending on factors such as diet and exercise habits.',
];